FROM node:14 as builder

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN ng build --prod

FROM nginx:latest

COPY --from=builder /usr/src/app/dist/blog-app /usr/share/nginx/html

EXPOSE 80
