version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    ports:
      - '3001:3000'
    volumes:
      - './nodejs:/usr/src/app'
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - './data:/data/db'
